# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    JNI_PATH: libretro
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile.libretro
    CORENAME: dosbox_svn

# Core definitions
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

  ################################## CONSOLES ################################
  # Nintendo 3DS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ctr-static.yml'

  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

  # PlayStation Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

################################### DESKTOPS #################################
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  variables:
    platform: win
    BUNDLED_SDL: 0
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs
  variables:
    BUNDLED_SDL: 1
  cache:
    key: "$CI_COMMIT_REF_SLUG-linux-x64-1"
    untracked: false
    paths:
      - libretro/deps_bin/
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - strip ${MAKEFILE_PATH}/${CORENAME}_libretro.so

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-armeabi-v7a-1"
    untracked: false
    paths:
      - libretro/deps_bin/

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-arm64-v8a-1"
    untracked: false
    paths:
      - libretro/deps_bin/

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-x86_64-1"
    untracked: false
    paths:
      - libretro/deps_bin/

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-jni-x86
    - .core-defs
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-x86-1"
    untracked: false
    paths:
      - libretro/deps_bin/

# Nintendo 3DS
libretro-build-ctr:
  extends:
    - .libretro-ctr-static-retroarch-master
    - .core-defs
  variables:
    BUNDLED_SDL: 0
  cache:
    key: "$CI_COMMIT_REF_SLUG-ctr-1"
    untracked: false
    paths:
      - libretro/deps_bin/

# Nintendo Switch
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs
  variables:
    BUNDLED_SDL: 0
  cache:
    key: "$CI_COMMIT_REF_SLUG-libnx-aarch64-1"
    untracked: false
    paths:
      - libretro/deps_bin/

# PlayStation Vita
libretro-build-vita:
  extends:
    - .libretro-vita-static-retroarch-master
    - .core-defs
  variables:
    BUNDLED_SDL: 0
  cache:
    key: "$CI_COMMIT_REF_SLUG-vita-1"
    untracked: false
    paths:
      - libretro/deps_bin/
